-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 16:58:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foodForAll
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foodForAll
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foodForAll` DEFAULT CHARACTER SET utf8 ;
USE `foodForAll` ;

-- -----------------------------------------------------
-- Table `foodForAll`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodForAll`.`community` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodForAll`.`beneficiaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodForAll`.`beneficiaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `stratus` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `community_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_children_community_idx` (`community_id` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_children_community`
    FOREIGN KEY (`community_id`)
    REFERENCES `foodForAll`.`community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodForAll`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodForAll`.`donor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `community_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_donor_community1_idx` (`community_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `fk_donor_community1`
    FOREIGN KEY (`community_id`)
    REFERENCES `foodForAll`.`community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodForAll`.`feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodForAll`.`feed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `donor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feed_donor1_idx` (`donor_id` ASC),
  CONSTRAINT `fk_feed_donor1`
    FOREIGN KEY (`donor_id`)
    REFERENCES `foodForAll`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into foodforall.community (name) values ("Usaquen");
insert into foodforall.community (name) values ("Chapinero");
insert into foodforall.community (name) values ("Santa Fe");
insert into foodforall.community (name) values ("San Cristobal");
insert into foodforall.community (name) values ("Usme");
insert into foodforall.community (name) values ("Tunjuelito");
insert into foodforall.community (name) values ("Bosa");
insert into foodforall.community (name) values ("Kennedy");
insert into foodforall.community (name) values ("Fontibon");
insert into foodforall.community (name) values ("Engativa");
insert into foodforall.community (name) values ("Suba");
insert into foodforall.community (name) values ("Barrios Unidos");
insert into foodforall.community (name) values ("Teusaquillo");
insert into foodforall.community (name) values ("Los Martires");
insert into foodforall.community (name) values ("Antonio Nariño");
insert into foodforall.community (name) values ("Puente Aranda");
insert into foodforall.community (name) values ("Candelaria");
insert into foodforall.community (name) values ("Rafael Uribe Uribe");
insert into foodforall.community (name) values ("Ciudad Bolivar");
insert into foodforall.community (name) values ("Sumapaz");